### https://www.kaggle.com/code/antaresnyc/prediction-with-random-forest-and-xgboost/notebook

### About this file
16S rRNA sequence of gut microbiota associated with autism spectrum disorders patients.
Here we report 16S rRNA data in gut microbiota of autism spectrum disorders compared with healthy volunteers. A total of 1322 operational taxonomic units (OTUs) were identified in the sequence data. The Bacteroidetes and Firmicutes were both dominated phylum in ausitic subjects and healthy controls. Phylum level analysis showed a clear alteration of the bacterial gut community in ASD characterized by a higher Firmicutes (P < 0.05), Proteobacteria (P < 0.001), and Actinobacteria (P < 0.001) than that in healthy controls. However, Bacteroidetes were significantly decreased in ASD patients (P < 0.001).

### 해석
자폐 스펙트럼 장애(ASD)환자와 관련된 장내미생물의 16S rRNA 서열이다.
여기서 우리는 자폐 스펙트럼 장애의 장내 세균총(gut microbiota)에서 16S rRNA 데이터를 건강한 지원자와 비교한다.
총 1322개의 조작상분류단위(OTU)가 시퀀스 데이터에서 확인되었다.
Bacteroidetes 와 Firmicutes는 둘 다 자폐증환자와 건강한 대조군에서 지배적인 phylum(문) 이었다.
Phylum level analysis는 건강한 대조군보다 더 높은 Firmicutes(P < 0.05), Proteobaceria(P < 0.001), Actinobaceria(P < 0.001)로 특징지어지는 ASD에서 bacterial gut community의 명확한 변화를 보여주었다. 그러나 ASD 환자에서 Bacteroidetes는 유의하게 감소하였다(P < 0.001).

### From the Abstract:

Autism Spectrum Disorder (ASD) is a severe neurodevelopmental disorder. To enhance the understanding of the gut microbiota structure in ASD children at different ages as well as the relationship between gut microbiota and fecal metabolites, we first used the 16S rRNA sequencing to evaluate the gut microbial population in a cohort of 143 children aged 2–13 years old. We found that the α-diversity of ASD group showed no significant change with age, while the TD group showed increased α-diversity with age, which indicates that the compositional development of the gut microbiota in ASD varies at different ages in ways that are not consistent with TD group. Recent studies have shown that chronic constipation is one of the most commonly obvious gastrointestinal (GI) symptoms along with ASD core symptoms. To further investigate the potential interaction effects between ASD and GI symptoms, the 30 C-ASD and their aged-matched TD were picked out to perform metagenomics analysis. We observed that C-ASD group displayed decreased diversity, depletion of species of Sutterella, Prevotella, and Bacteroides as well as dysregulation of associated metabolism activities, which may involve in the pathogenesis of C-ASD. Consistent with metagenomic analysis, liquid chromatography-mass spectrometry (LC/MS) revealed some of the differential metabolites between C-ASD and TD group were involved in the metabolic network of neurotransmitters including serotonin, dopamine, histidine, and GABA. Furthermore, we found these differences in metabolites were associated with altered abundance of specific bacteria. The study suggested possible future modalities for ASD intervention through targeting the specific bacteria associated with neurotransmitter metabolism.

### 해석

자폐스펙트럼장애(ASD)는 심각한 신경 발당 장애이다. 다양한 연령의 ASD 아동의 장내 미생물 구조와 장내 미생물과 대변 대사물간의 관계에 대한 이해를 높이기 위해 먼저 16S rRNA 염기 서열을 사용하여 2-13세 아동 143명의 코호트에서 장내 미생물 개체군을 평가했다. ASD 그룹의 alpha-다양성은 연령에 따라 큰 변화를 보이지 않는 반면 TD 그룹은 연령에 따라 증가된 alpha-다양성을 보여 ASD에서 장내 미생물군의 구성 발달이 TD그룹과 일치하지 않는 방식으로 다양함을 보여주었다. 최근 연구에 따르면 만성 변비는 ASD 핵심증상과 함께 가장 일반적으로 명백한 gastrointestinal(GI)증상 중 하나이다. ASD와 GI증상 사이의 잠재적 상호작용 효과를 추가로 조사하기 위해 30개의 C-ASD와 그들의 aged-matched TD를 선택하여 metagenomics analysis을 수행했다. 우리는 C-ASD 그룹이 감소된 다양성, Sutterella, Prevotella 및 Bacteroides종의 고갈 및 C-ASD의 발병에 관련될 수 있는 관련 신진대사 활동의 조절 장애를 나타내는 것을 관찰했다. metagenomic analysis과 일관되게, liquid chromatography-mass spectrometry (LC/MS)은 C-ASD와 TD그룹 사이의 일부 대사물질 차이가  serotonin, dopamine, histidine 및 GABA를 포함한 신경전달물질의 대사 네트워크에 관련되어 있음을 보여주었다. 더하여, 우리는 대사물질의 이러한 차이가 특정 박테리아의 변화된 abundance와 관련이 있다는 것을 발견했다. 이 연구는 신경전달물질 대사와 관련된 특정 박테리아를 표적화함으로써 ASD 개입을 위한 미래 양상을 제안했다.  

### The dataset is from the research paper by Zhou Dan et al. published on April 21st of 2020
#### https://www.tandfonline.com/doi/full/10.1080/19490976.2020.1747329

In [1]:
import numpy as np 
import pandas as pd
import os

In [2]:
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.metrics import f1_score, roc_auc_score, confusion_matrix, precision_recall_curve, auc, roc_curve, recall_score, precision_score


# some hyper parameters
SEED = 303
test_train_split_SEED = 303
# FOLDS = 10
show_fold_stats = True
VERBOSE = 0
FOLDS = 5

In [3]:
pd_abundance = pd.read_csv('./GSE113690_Autism_16S_rRNA_OTU_assignment_and_abundance.csv')
pd_meta_abundance = pd.read_csv('./ASD meta abundance.csv')

###  논문 링크

### https://en.wikipedia.org/wiki/Operational_taxonomic_unit

### taxonomy : 분류체계 

In [20]:
pd_abundance

OTU                                           taxonomy  A1  A10  \
0        OTU1  d__Bacteria;_k__norank;_p__Firmicutes;_c__Clos...   0    0   
1        OTU2  d__Bacteria;_k__norank;_p__Proteobacteria;_c__...   0    0   
2        OTU3  d__Bacteria;_k__norank;_p__Firmicutes;_c__Erys...   0    0   
3        OTU4  d__Bacteria;_k__norank;_p__Firmicutes;_c__Baci...   0    0   
4        OTU5  d__Bacteria;_k__norank;_p__Tenericutes;_c__Mol...   0    0   
...       ...                                                ...  ..  ...   
1317  OTU1334  d__Bacteria;_k__norank;_p__Bacteroidetes;_c__B...   0    0   
1318  OTU1335  d__Bacteria;_k__norank;_p__Actinobacteria;_c__...   0    0   
1319  OTU1336  d__Bacteria;_k__norank;_p__Firmicutes;_c__Clos...   0    0   
1320  OTU1337  d__Bacteria;_k__norank;_p__Firmicutes;_c__Clos...   0    0   
1321  OTU1338  d__Bacteria;_k__norank;_p__Firmicutes;_c__Clos...   0    0   

      A100  A101  A102  A104  A105  A106  ...  B52  B54  B55  B56  B57  B58  \
0        0     0     0     0     1     0  ...    0    0    0    0    0    0   
1        0     0     0     0     0     0  ...    0    0    0    0    0    0   
2        0     0     0     0     0     2  ...    0    0    0    0    0    0   
3        0     0     0     0     0     0  ...    0    0    0    0    0    0   
4        1     0     0     1     0     3  ...    0    0    0    0    0    0   
...    ...   ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1317     0     0     0     0     0     0  ...    0    0    0    0    0    0   
1318     0     0     0     0     0     0  ...    0    0    0    0    0    0   
1319     0     0     0     0     0     0  ...    0    0    0    0    0    0   
1320     0     0     0     0     0     0  ...    0    0    0    0    0    0   
1321     0     0     0     0     0     0  ...    0    0    0    0    0    0   

      B59  B6  B60  B61  
0       0   0    0    0  
1       0   0    0    0  
2       0   0    0    0  
3       0   0    1    0  
4       0   0    0    0  
...   ...  ..  ...  ...  
1317    0   0    0    0  
1318    0   0    0    0  
1319    0   0    0    0  
1320    0   0    0    0  
1321    0   0    0    0  

[1322 rows x 256 columns]

In [10]:
pd_abundance['A3'].unique()

array([   0,    1,    6,    3,   10,    5,    9,  106,  203,   20,   14,
        228,   11,   19, 1523,   65,   38,   68,  552,    2,  171,   29,
        758,    4,   17,  328,   12,    7,  524, 1603,    8,  288,   93,
         24,  128,   30,  234,   47,   13, 2751,   57,   18,  158,   42,
        403, 2449,  153,  830,   15,  143,  131,  136,  182,   34,  325,
        295,   82,   97,   71,   78,  154,  244,  353,  107,  218,   26,
        577,  370,   51,  833,  165,   28,   95,   31,   44,  971,   98,
        208, 1345,   46,  313,   16,   73,   96,  440,  542,   36,   39,
        109,  284,  318,  139,   21,   61,  112,   23,  121,   84,   37,
         27,  246,  209,  424,  119,  162, 1141,   53,  127,   32,  146,
        231,  210,  159,  975,  114,   67,   35,   58,   33], dtype=int64)

In [8]:
#pd_meta_abundance

In [17]:
taxa = pd_abundance[['OTU', 'taxonomy']].set_index('OTU')
pd_abundance_T = pd_abundance.drop('taxonomy', axis=1).set_index('OTU').transpose()

target = pd_abundance_T.index.to_list()
# A: TD 샘플 
# B: ASD 샘플
binary_target = np.array([1 if t.startswith('A') else 0 for t in target ])

total_species = pd_abundance_T.sum(axis = 1)
abs_abundance = 31757
pd_rel_abundance = pd_abundance_T / abs_abundance 

In [13]:
taxa

taxonomy
OTU                                                       
OTU1     d__Bacteria;_k__norank;_p__Firmicutes;_c__Clos...
OTU2     d__Bacteria;_k__norank;_p__Proteobacteria;_c__...
OTU3     d__Bacteria;_k__norank;_p__Firmicutes;_c__Erys...
OTU4     d__Bacteria;_k__norank;_p__Firmicutes;_c__Baci...
OTU5     d__Bacteria;_k__norank;_p__Tenericutes;_c__Mol...
...                                                    ...
OTU1334  d__Bacteria;_k__norank;_p__Bacteroidetes;_c__B...
OTU1335  d__Bacteria;_k__norank;_p__Actinobacteria;_c__...
OTU1336  d__Bacteria;_k__norank;_p__Firmicutes;_c__Clos...
OTU1337  d__Bacteria;_k__norank;_p__Firmicutes;_c__Clos...
OTU1338  d__Bacteria;_k__norank;_p__Firmicutes;_c__Clos...

[1322 rows x 1 columns]

In [14]:
pd_abundance_T

OTU   OTU1  OTU2  OTU3  OTU4  OTU5  OTU6  OTU7  OTU8  OTU9  OTU10  ...  \
A1       0     0     0     0     0     1     0     0    50      0  ...   
A10      0     0     0     0     0     0     0     0    10      2  ...   
A100     0     0     0     0     1     0     0   485    13      0  ...   
A101     0     0     0     0     0     0     1   142    17      0  ...   
A102     0     0     0     0     0     0     0     1     9      0  ...   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...   
B58      0     0     0     0     0     1     1     0     0      0  ...   
B59      0     0     0     0     0     0     0    25     2      0  ...   
B6       0     0     0     0     0     0     0    20     7      0  ...   
B60      0     0     0     1     0     0     1     0    13      0  ...   
B61      0     0     0     0     0     0     2     0     3      0  ...   

OTU   OTU1329  OTU1330  OTU1331  OTU1332  OTU1333  OTU1334  OTU1335  OTU1336  \
A1          1        0        1        0        0        0        0        0   
A10         5        0        0        0        0        0        0        0   
A100        0        0        0        0        0        0        0        0   
A101        0        1        0        0        0        0        0        0   
A102        1        0        0        0        0        0        0        0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
B58         0        0        0        0        0        0        0        0   
B59         1        0        0        0        0        0        0        0   
B6          1        0        0        0        0        0        0        0   
B60         0        0        0        0        0        0        0        0   
B61         0        0        0        0        0        0        0        0   

OTU   OTU1337  OTU1338  
A1          0        0  
A10         0        0  
A100        0        0  
A101        0        0  
A102        0        0  
...       ...      ...  
B58         0        0  
B59         0        0  
B6          0        0  
B60         0        0  
B61         0        0  

[254 rows x 1322 columns]

In [45]:
print("Group A(TD) : {} 명".format(len(binary_target[binary_target==1])))
print("Group B(ASD) : {} 명".format(len(binary_target[binary_target==0])))

Group A(TD) : 143 명
Group B(ASD) : 111 명


In [32]:
total_species

A1      31757
A10     31757
A100    31757
A101    31757
A102    31757
        ...  
B58     31757
B59     31757
B6      31757
B60     31757
B61     31757
Length: 254, dtype: int64

In [39]:
pd_rel_abundance

OTU   OTU1  OTU2  OTU3      OTU4      OTU5      OTU6      OTU7      OTU8  \
A1     0.0   0.0   0.0  0.000000  0.000000  0.000031  0.000000  0.000000   
A10    0.0   0.0   0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
A100   0.0   0.0   0.0  0.000000  0.000031  0.000000  0.000000  0.015272   
A101   0.0   0.0   0.0  0.000000  0.000000  0.000000  0.000031  0.004471   
A102   0.0   0.0   0.0  0.000000  0.000000  0.000000  0.000000  0.000031   
...    ...   ...   ...       ...       ...       ...       ...       ...   
B58    0.0   0.0   0.0  0.000000  0.000000  0.000031  0.000031  0.000000   
B59    0.0   0.0   0.0  0.000000  0.000000  0.000000  0.000000  0.000787   
B6     0.0   0.0   0.0  0.000000  0.000000  0.000000  0.000000  0.000630   
B60    0.0   0.0   0.0  0.000031  0.000000  0.000000  0.000031  0.000000   
B61    0.0   0.0   0.0  0.000000  0.000000  0.000000  0.000063  0.000000   

OTU       OTU9     OTU10  ...   OTU1329   OTU1330   OTU1331  OTU1332  OTU1333  \
A1    0.001574  0.000000  ...  0.000031  0.000000  0.000031      0.0      0.0   
A10   0.000315  0.000063  ...  0.000157  0.000000  0.000000      0.0      0.0   
A100  0.000409  0.000000  ...  0.000000  0.000000  0.000000      0.0      0.0   
A101  0.000535  0.000000  ...  0.000000  0.000031  0.000000      0.0      0.0   
A102  0.000283  0.000000  ...  0.000031  0.000000  0.000000      0.0      0.0   
...        ...       ...  ...       ...       ...       ...      ...      ...   
B58   0.000000  0.000000  ...  0.000000  0.000000  0.000000      0.0      0.0   
B59   0.000063  0.000000  ...  0.000031  0.000000  0.000000      0.0      0.0   
B6    0.000220  0.000000  ...  0.000031  0.000000  0.000000      0.0      0.0   
B60   0.000409  0.000000  ...  0.000000  0.000000  0.000000      0.0      0.0   
B61   0.000094  0.000000  ...  0.000000  0.000000  0.000000      0.0      0.0   

OTU   OTU1334  OTU1335  OTU1336  OTU1337  OTU1338  
A1        0.0      0.0      0.0      0.0      0.0  
A10       0.0      0.0      0.0      0.0      0.0  
A100      0.0      0.0      0.0      0.0      0.0  
A101      0.0      0.0      0.0      0.0      0.0  
A102      0.0      0.0      0.0      0.0      0.0  
...       ...      ...      ...      ...      ...  
B58       0.0      0.0      0.0      0.0      0.0  
B59       0.0      0.0      0.0      0.0      0.0  
B6        0.0      0.0      0.0      0.0      0.0  
B60       0.0      0.0      0.0      0.0      0.0  
B61       0.0      0.0      0.0      0.0      0.0  

[254 rows x 1322 columns]

### Train & Test Split

In [40]:
#Lets put aside a small test set, so we can check performance of different classifiers against it
disease_train, disease_test, disease_y_train, disease_y_test = train_test_split(pd_rel_abundance, binary_target, test_size = 0.2,  random_state = test_train_split_SEED , shuffle = True)   

In [42]:
disease_train

OTU   OTU1  OTU2      OTU3      OTU4      OTU5      OTU6      OTU7      OTU8  \
A14    0.0   0.0  0.000031  0.000031  0.000000  0.000000  0.000000  0.000031   
A156   0.0   0.0  0.000000  0.000000  0.000000  0.000031  0.000000  0.009636   
B133   0.0   0.0  0.000000  0.000000  0.000031  0.000000  0.000000  0.000063   
A148   0.0   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
B1     0.0   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
...    ...   ...       ...       ...       ...       ...       ...       ...   
B120   0.0   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
A84    0.0   0.0  0.000000  0.000000  0.000157  0.000000  0.000031  0.005416   
A117   0.0   0.0  0.000000  0.000000  0.000126  0.000000  0.000000  0.000000   
A78    0.0   0.0  0.000000  0.000031  0.000000  0.000000  0.000063  0.000315   
A159   0.0   0.0  0.000126  0.000000  0.000000  0.000000  0.000000  0.000000   

OTU       OTU9     OTU10  ...   OTU1329   OTU1330   OTU1331   OTU1332  \
A14   0.000693  0.000000  ...  0.000000  0.000031  0.000000  0.000000   
A156  0.001102  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
B133  0.000441  0.000000  ...  0.000000  0.000000  0.000031  0.000000   
A148  0.000094  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
B1    0.000220  0.000000  ...  0.000063  0.000000  0.000031  0.000000   
...        ...       ...  ...       ...       ...       ...       ...   
B120  0.000598  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
A84   0.000724  0.000031  ...  0.000000  0.000000  0.000000  0.000031   
A117  0.000126  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
A78   0.000346  0.000000  ...  0.000000  0.000031  0.000000  0.000000   
A159  0.001448  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

OTU   OTU1333   OTU1334  OTU1335  OTU1336  OTU1337  OTU1338  
A14       0.0  0.000000      0.0      0.0      0.0      0.0  
A156      0.0  0.000000      0.0      0.0      0.0      0.0  
B133      0.0  0.000000      0.0      0.0      0.0      0.0  
A148      0.0  0.000000      0.0      0.0      0.0      0.0  
B1        0.0  0.000000      0.0      0.0      0.0      0.0  
...       ...       ...      ...      ...      ...      ...  
B120      0.0  0.000000      0.0      0.0      0.0      0.0  
A84       0.0  0.000000      0.0      0.0      0.0      0.0  
A117      0.0  0.000000      0.0      0.0      0.0      0.0  
A78       0.0  0.000126      0.0      0.0      0.0      0.0  
A159      0.0  0.000000      0.0      0.0      0.0      0.0  

[203 rows x 1322 columns]

In [43]:
disease_y_train

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1])

### RandomForest & XGBoost

In [50]:
skf = StratifiedKFold(n_splits = FOLDS, shuffle = True, random_state = SEED)

for fold, (idxT,idxV) in enumerate(skf.split(disease_train, disease_y_train)):

    X_train = disease_train.iloc[idxT]
    X_val = disease_train.iloc[idxV]
    y_train = disease_y_train[idxT]
    y_val = disease_y_train[idxV]

    clf = RandomForestClassifier(n_estimators = 500, random_state = SEED, verbose = 0)
    clf.fit(X_train, y_train )

    RF_pred_class = clf.predict(X_val)
    RF_preds = clf.predict_proba(X_val)
    
    RF_AUC_test_score = roc_auc_score(y_val, RF_preds[:,1])
    RF_f1_test = f1_score(y_val, RF_pred_class)
    RF_recall_test = recall_score(y_val, RF_pred_class)
    RF_precision_test = precision_score(y_val, RF_pred_class)
    
    if show_fold_stats:
        print('-' * 80)
        print('Fold : %s'%(fold+1))
        print('ROC AUC score for RandomForest model, validation set: %.4f'%RF_AUC_test_score)
        print('F1 : %.4f, Recall : %.4f , Precision : %.4f'%(RF_f1_test, RF_recall_test, RF_precision_test))
        print(confusion_matrix(y_val, RF_pred_class))
    
    XGB_model = XGBClassifier(n_estimators=5000, max_depth=None, 
                        learning_rate=0.005,
                        objective='binary:logistic', 
                        metric='auc',
                        verbosity  = VERBOSE,
                        # tree_method = 'gpu_hist',
                        #use_label_encoder=False,
                        n_jobs=-1, random_state  = SEED )
    
    XGB_model.fit(X_train, y_train,
                    eval_set = [(X_val, y_val)],
                    eval_metric=['logloss'],
                    early_stopping_rounds = 100, verbose = VERBOSE )
        
    XGB_preds = XGB_model.predict_proba(X_val)
    XGB_class = XGB_model.predict(X_val)

    XGB_score = roc_auc_score(y_val, XGB_preds[:,1])
    XGB_f1 = f1_score(y_val, XGB_class)
    XGB_recall = recall_score(y_val, XGB_class)
    XGB_precision = precision_score(y_val, XGB_class)

    if show_fold_stats:        
        print('ROC AUC score for XGBoost model, validation set: %.4f'%XGB_score)
        print('F1 : %.4f, Recall : %.4f , Precision : %.4f'%(XGB_f1, XGB_recall, XGB_precision))
        print(confusion_matrix(y_val, XGB_class))

    RF_preds_test = clf.predict_proba(disease_test) #초기 train &test split 때 나눴던 데이터로 predict
    XGB_preds_test = XGB_model.predict_proba(disease_test) #초기 train &test split 때 나눴던 데이터로 predict
    avg_preds_test = (RF_preds_test[:,1] + XGB_preds_test[:,1]) / 2

    RF_test_AUC = roc_auc_score(disease_y_test, RF_preds_test[:,1])
    print('ROC AUC score for RF for test set: %.4f'%RF_test_AUC)
    XGB_test_AUC = roc_auc_score(disease_y_test, XGB_preds_test[:,1])
    print('ROC AUC score for XGBoost model test set: %.4f'%XGB_test_AUC)
    average_AUC = roc_auc_score(disease_y_test, avg_preds_test )
    print('ROC AUC score averaged between 2 models for test set: %.4f'%average_AUC)
    
    avg_class = np.where(avg_preds_test < 0.7, 0, 1)
    print('F1 : %.4f, Recall : %.4f , Precision : %.4f'%(f1_score(disease_y_test, avg_class), recall_score(disease_y_test, avg_class), precision_score(disease_y_test, avg_class)))
    print(confusion_matrix(disease_y_test, avg_class))

--------------------------------------------------------------------------------
Fold : 1
ROC AUC score for RandomForest model, validation set: 0.9734
F1 : 0.9130, Recall : 0.9130 , Precision : 0.9130
[[16  2]
 [ 2 21]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


ROC AUC score for XGBoost model, validation set: 0.9734
F1 : 0.9565, Recall : 0.9565 , Precision : 0.9565
[[17  1]
 [ 1 22]]
ROC AUC score for RF for test set: 0.9371
ROC AUC score for XGBoost model test set: 0.9500
ROC AUC score averaged between 2 models for test set: 0.9516
F1 : 0.7692, Recall : 0.6452 , Precision : 0.9524
[[19  1]
 [11 20]]
--------------------------------------------------------------------------------
Fold : 2
ROC AUC score for RandomForest model, validation set: 0.9650
F1 : 0.9388, Recall : 1.0000 , Precision : 0.8846
[[15  3]
 [ 0 23]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


ROC AUC score for XGBoost model, validation set: 0.9903
F1 : 0.9388, Recall : 1.0000 , Precision : 0.8846
[[15  3]
 [ 0 23]]
ROC AUC score for RF for test set: 0.9516
ROC AUC score for XGBoost model test set: 0.9694
ROC AUC score averaged between 2 models for test set: 0.9839
F1 : 0.8772, Recall : 0.8065 , Precision : 0.9615
[[19  1]
 [ 6 25]]
--------------------------------------------------------------------------------
Fold : 3
ROC AUC score for RandomForest model, validation set: 0.9856
F1 : 0.9302, Recall : 0.9091 , Precision : 0.9524
[[18  1]
 [ 2 20]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


ROC AUC score for XGBoost model, validation set: 0.9880
F1 : 0.9302, Recall : 0.9091 , Precision : 0.9524
[[18  1]
 [ 2 20]]
ROC AUC score for RF for test set: 0.9847
ROC AUC score for XGBoost model test set: 0.9855
ROC AUC score averaged between 2 models for test set: 0.9903
F1 : 0.8727, Recall : 0.7742 , Precision : 1.0000
[[20  0]
 [ 7 24]]
--------------------------------------------------------------------------------
Fold : 4
ROC AUC score for RandomForest model, validation set: 0.9520
F1 : 0.9362, Recall : 1.0000 , Precision : 0.8800
[[15  3]
 [ 0 22]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


ROC AUC score for XGBoost model, validation set: 0.9470
F1 : 0.8889, Recall : 0.9091 , Precision : 0.8696
[[15  3]
 [ 2 20]]
ROC AUC score for RF for test set: 0.9758
ROC AUC score for XGBoost model test set: 0.9548
ROC AUC score averaged between 2 models for test set: 0.9758
F1 : 0.8519, Recall : 0.7419 , Precision : 1.0000
[[20  0]
 [ 8 23]]
--------------------------------------------------------------------------------
Fold : 5
ROC AUC score for RandomForest model, validation set: 0.9381
F1 : 0.9167, Recall : 1.0000 , Precision : 0.8462
[[14  4]
 [ 0 22]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


ROC AUC score for XGBoost model, validation set: 0.9444
F1 : 0.8571, Recall : 0.9545 , Precision : 0.7778
[[12  6]
 [ 1 21]]
ROC AUC score for RF for test set: 0.9468
ROC AUC score for XGBoost model test set: 0.9435
ROC AUC score averaged between 2 models for test set: 0.9581
F1 : 0.8571, Recall : 0.7742 , Precision : 0.9600
[[19  1]
 [ 7 24]]


### Lets try metagenomic data: 30 samples with ASD and 30 TD

In [51]:
# exclude absent spcecies
pd_meta_abundance = pd_meta_abundance[pd_meta_abundance.sum(axis = 1) !=0]

C:\Users\User\AppData\Local\Temp\ipykernel_1684\1316083498.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  pd_meta_abundance = pd_meta_abundance[pd_meta_abundance.sum(axis = 1) !=0]


In [52]:
pd_meta_abundance

Taxonomy    A3    A5    A6  \
0     g__Faecalibacterium;s__Faecalibacterium prausn...  4988  5060  2905   
1                 g__Hungatella;s__Hungatella hathewayi  5803  5612  4109   
2          g__Clostridium;s__uncultured Clostridium sp.  3793  2795  1355   
3              g__Butyricimonas;s__Butyricimonas virosa    64  1385   725   
4                g__Alistipes;s__Alistipes indistinctus    15    20   723   
...                                                 ...   ...   ...   ...   
5452            g__Unclassified;s__Skermania phage SPI1     0     0     0   
5453         g__Unclassified;s__Vibrio phage vB_VhaS-tm     0     0     0   
5454  g__Unclassified;s__uncultured Mediterranean ph...     0     0     0   
5455  g__Unclassified;s__uncultured Mediterranean ph...     0     0     0   
5456                g__Unclassified;s__uncultured virus     0     0     0   

        A9   A31   A51   A52   A53   A54  ...  B120  B127  B132  B141  B142  \
0     5745  4822  3889  4646  6337  5064  ...  4471  5868  6561  4910  4492   
1     1432  2652  4175  3891   894  4903  ...  2126  4429  2598  4222  4925   
2     5558  5383  3505  5541  4429  4121  ...  4085  6041  6188  3960  4403   
3     1553    40    53    33   175    58  ...  2065    21    27    55    35   
4      620  3261    43    83    37    43  ...    90    22    30  1027  2641   
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   
5452     0     0     0     0     0     0  ...     0     0     0     0     0   
5453     0     0     0     0     0     0  ...     0     1     0     0     0   
5454     0     0     0     0     0     0  ...     0     0     0     0     0   
5455     1     0     0     0     0     0  ...     0     1     1     0     0   
5456     0     0     0     0     0     0  ...     0     0     0     0     0   

      B143  B152  B156  B158  B164  
0     2812  5303  4205  3430  4563  
1     5753  1261  1822  2478  4868  
2     2841  2746  3808  3856  3211  
3        8   884    13     3   218  
4        4  1587  2223     6  1473  
...    ...   ...   ...   ...   ...  
5452     0     0     0     0     0  
5453     0     0     0     0     0  
5454     0     0     0     0     0  
5455     0     0     0     0     0  
5456     0     0     0     0     0  

[5457 rows x 61 columns]

In [57]:
pd_meta_abndc = pd_meta_abundance.drop(['Taxonomy'], axis=1).T
target = pd_meta_abndc.index.to_list()
# A: TD 샘플 
# B: ASD 샘플
binary_target = np.array([1 if t.startswith('A') else 0 for t in target ])

In [58]:
pd_meta_abndc

0     1     2     3     4     5     6     7     8     9     ...  5447  \
A3    4988  5803  3793    64    15   100  2119    12   453  1266  ...     0   
A5    5060  5612  2795  1385    20    29  1230    24   691  1682  ...     0   
A6    2905  4109  1355   725   723    11  1322     1  2278    43  ...     0   
A9    5745  1432  5558  1553   620  1320  2675    44   107  1726  ...     0   
A31   4822  2652  5383    40  3261    51  1470    26   342  1804  ...     0   
A51   3889  4175  3505    53    43    45  2262     9  1304  1441  ...     0   
A52   4646  3891  5541    33    83    52  2984    25  1400  2691  ...     0   
A53   6337   894  4429   175    37    64  2004    19  1207  1886  ...     0   
A54   5064  4903  4121    58    43    60  1904    17  2034   919  ...     0   
A59   6359  2970  3258  1636  1114   896  1227    17  2051  2215  ...     0   
A67   3194  4029  1901  1170  2531    26   821    15    20  1063  ...     0   
A68   4486  1266  2940    80   207    54  1420     7   105  1765  ...     0   
A69   3807  4822  3820    59    59    35   167     9   752   146  ...     0   
A71   6208  1635  5118    77    50  1953  1696   127   527  2171  ...     0   
A73   3008  4761  1582  1364    55    23  1389    24   478  1679  ...     0   
A76   5628  1366  4168    67  1194    54  1192    17   423   948  ...     0   
A78   5732  1867  3831    63    68    50  1772    15   260   632  ...     0   
A87   5240  2065  3464     7    49    70  1807    15  2534  1231  ...     0   
A89   3616  4777  2942   999   979    55   144    21  1611  1110  ...     0   
A93   3355  5954  3291    39    10    36  1291    18  2758  1317  ...     0   
A101  3833  6849  4586  3285  3159  1109  1876    31   438  2153  ...     0   
A109  3771  4390  1014    30    61    25   245    17  1595    82  ...     0   
A113  5489  2091  4100    54  2606    48  1945    17  2038  1116  ...     0   
A114  6762  1638  4336  1168  2821  3034  2036    74   747  2065  ...     0   
A115  3045  4613  2301    50    21    67  1489    11  1336  1033  ...     0   
A142  6205  2601  6372    38  2276  1196  1754    42   646  1169  ...     0   
A144  6048  1892  4020    49     3   123  1556  2940   909  1583  ...     0   
A149  5418  3267  3511    27    34   160  2035    20   227  1016  ...     0   
A164  5120  2294  4328  1685  2681    49  2370    35   402  1592  ...     0   
A165  8504  2978  3906   838  2103  1158  2136    82   539  1051  ...     1   
B1    4269  1217  3853  1624  2452   185  1358    30   145  1949  ...     0   
B2    4397  6238  4624     1     3    41  1850    13  2524  1858  ...     0   
B3    4499  2325  3842   703   819    24  1504   381  2208  2209  ...     0   
B5    6126  5004  4399    43  2761  1418  1566  1569   453  1979  ...     0   
B6    7020  2829  3916    46   691   119  1831    15   236  2451  ...     0   
B7    5404  2192  3355  1505  2768    23   643     4  2670   750  ...     0   
B8    4404  2921  5165    32    25   757  2117    22  1656  1563  ...     0   
B13   5811  4303  4453  1474  1095   629  1581    16  2566  2502  ...     0   
B14   3360  2793  1999     2    13    12  1229     2   128  1262  ...     0   
B28   4141  3671  3974    52     4    37  2649    53    46  1989  ...     0   
B29   2880  5350  1185     4     4     7  1284    16  2564  1146  ...     0   
B36   3805  4566  3895     5     6     8   818    40  1438  2241  ...     0   
B37   4168  3984  2710    43   356    19  1451    61  2142  1341  ...     0   
B94   4543  5597  3425  1449  2380    65  1999    57   323  1038  ...     0   
B99   2804  5191  1559     5    23    13   108   888   563   572  ...     0   
B103  5728  2204  4902    36  3089   851  2361    20   776  1756  ...     0   
B106  3827  5523  3016    34    33    34  2246     9   437   727  ...     0   
B111  6030  1556  6066    37  2052   208  1839  1718   475   653  ...     0   
B114  4950  4983  5082   113  2801   803  1769  1473  1537  2117  ...     0   
B115  4749  5993  3764    46     2    30  2045    33   5

In [63]:
#target

In [61]:
len(binary_target)

60

In [62]:
# this subset of data is too small to have a separate test set, so we'd have to rely on CV only
skf = StratifiedKFold(n_splits = FOLDS, shuffle = True, random_state = SEED)
for fold, (idxT,idxV) in enumerate(skf.split(pd_meta_abndc, binary_target)):

    X_train = pd_meta_abndc.iloc[idxT]
    X_val = pd_meta_abndc.iloc[idxV]
    y_train = binary_target[idxT]
    y_val = binary_target[idxV]

    clf = RandomForestClassifier(n_estimators = 500, random_state = SEED, verbose = 0)
    clf.fit(X_train, y_train )

    RF_pred_class = clf.predict(X_val)
    RF_preds = clf.predict_proba(X_val)
    
    RF_AUC_test_score = roc_auc_score(y_val, RF_preds[:,1])
    RF_f1_test = f1_score(y_val, RF_pred_class)
    RF_recall_test = recall_score(y_val, RF_pred_class)
    RF_precision_test = precision_score(y_val, RF_pred_class)
    
    if show_fold_stats:
        print('-' * 80)
        print('Fold : %s'%(fold+1))
        print('ROC AUC score for RandomForest model, validation set: %.4f'%RF_AUC_test_score)
        print('F1 : %.4f, Recall : %.4f , Precision : %.4f'%(RF_f1_test, RF_recall_test, RF_precision_test))
        print(confusion_matrix(y_val, RF_pred_class))
    
    XGB_model = XGBClassifier(n_estimators=5000, max_depth=None, 
                        learning_rate=0.005,
                        objective='binary:logistic', 
                        metric='auc',
                        verbosity  = VERBOSE,
                        # tree_method = 'gpu_hist',
                        use_label_encoder=False,
                        n_jobs=-1, random_state  = SEED )
    
    XGB_model.fit(X_train, y_train,
                    eval_set = [(X_val, y_val)],
                    eval_metric=['logloss'],
                    early_stopping_rounds = 100, verbose = VERBOSE )
        
    XGB_preds = XGB_model.predict_proba(X_val)
    XGB_class = XGB_model.predict(X_val)

    XGB_score = roc_auc_score(y_val, XGB_preds[:,1])
    XGB_f1 = f1_score(y_val, XGB_class)
    XGB_recall = recall_score(y_val, XGB_class)
    XGB_precision = precision_score(y_val, XGB_class)

    if show_fold_stats:        
        print('ROC AUC score for XGBoost model, validation set: %.4f'%XGB_score)
        print('F1 : %.4f, Recall : %.4f , Precision : %.4f'%(XGB_f1, XGB_recall, XGB_precision))
        print(confusion_matrix(y_val, XGB_class))

--------------------------------------------------------------------------------
Fold : 1
ROC AUC score for RandomForest model, validation set: 0.8056
F1 : 0.6667, Recall : 0.6667 , Precision : 0.6667
[[4 2]
 [2 4]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:1421: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


ROC AUC score for XGBoost model, validation set: 0.5833
F1 : 0.6154, Recall : 0.6667 , Precision : 0.5714
[[3 3]
 [2 4]]
--------------------------------------------------------------------------------
Fold : 2
ROC AUC score for RandomForest model, validation set: 0.9722
F1 : 0.8000, Recall : 0.6667 , Precision : 1.0000
[[6 0]
 [2 4]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:1421: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


ROC AUC score for XGBoost model, validation set: 1.0000
F1 : 0.9091, Recall : 0.8333 , Precision : 1.0000
[[6 0]
 [1 5]]
--------------------------------------------------------------------------------
Fold : 3
ROC AUC score for RandomForest model, validation set: 0.9722
F1 : 0.6667, Recall : 0.5000 , Precision : 1.0000
[[6 0]
 [3 3]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:1421: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


ROC AUC score for XGBoost model, validation set: 0.9167
F1 : 0.8000, Recall : 0.6667 , Precision : 1.0000
[[6 0]
 [2 4]]
--------------------------------------------------------------------------------
Fold : 4
ROC AUC score for RandomForest model, validation set: 0.9722
F1 : 0.8333, Recall : 0.8333 , Precision : 0.8333
[[5 1]
 [1 5]]


C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:1421: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\xgboost\sklearn.py:861: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


KeyboardInterrupt: 